---
# https://docs.cilium.io/en/stable/helm-reference/
kubeProxyReplacement: true
k8sServiceHost: "10.0.0.20"
k8sServicePort: 6443
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.244.0.0/16"
hubble:
  relay:
    enabled: false
  ui:
    enabled: false
