---
# https://docs.cilium.io/en/stable/helm-reference/

upgradeCompatibility: "1.17"

k8sServiceHost: "auto"
kubeProxyReplacement: true

ipam:
  mode: "kubernetes"

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
