---
- name: Set connection variables for initial setup
  set_fact:
    ansible_user: boot
    ansible_ssh_pass: boot
  no_log: true

- name: Create user
  user:
    name: "{{ ssh_username }}"
    shell: /bin/bash
    create_home: yes
    state: present
    password_lock: yes

- name: Add user to sudo group
  user:
    name: "{{ ssh_username }}"
    groups: sudo
    append: yes

- name: Ensure user .ssh directory exists
  file:
    path: "/home/{{ ssh_username }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"

- name: Add public keys to authorized_keys
  authorized_key:
    user: homekube
    key: "{{ lookup('file', item) }}"
    state: present
  with_fileglob:
    - "{{ role_path }}/files/pub_keys/*.pub"

- name: Configure sudoers for homekube user
  lineinfile:
    path: "/etc/sudoers.d/{{ ssh_username }}"
    line: "{{ ssh_username }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: "0440"
    create: yes
    validate: "visudo -cf %s"

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd
