---
- name: Get Kubernetes package version information
  vars:
    k8s_components:
      - containernetworking-plugins
      - kubeadm
      - kubectl
      - kubelet
      - runc
  block:
    - name: Get package information
      command: "apt-cache policy {{ item }}"
      register: version_output
      changed_when: false
      failed_when: version_output.rc != 0
      loop: "{{ k8s_components }}"

    - name: Print version information
      debug:
        msg: "{{ item }} - {{ version_output.results[k8s_components.index(item)].stdout_lines[1] }} - {{ version_output.results[k8s_components.index(item)].stdout_lines[2] }}"
      loop: "{{ k8s_components }}"

- name: Get containerd version
  command: "containerd --version"
  register: containerd_version
  changed_when: false
  failed_when: containerd_version.rc != 0

- name: Get latest containerd release
  uri:
    url: "https://api.github.com/repos/containerd/containerd/releases/latest"
    return_content: yes
    method: GET
  register: latest_release

- name: Set latest containerd version fact
  set_fact:
    containerd_latest_version: "{{ latest_release.json.tag_name }}"

- name: Print containerd version information
  debug:
    msg: "containerd - {{ containerd_version.stdout }} \n latest version - {{ containerd_latest_version }}"
