---
- name: Install kubelet kubeadm kubectl
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl

- name: Hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold
