# source: Kube the hard way TODO: streamline
version = 2

[plugins."io.containerd.grpc.v1.cri"]
  [plugins."io.containerd.grpc.v1.cri".containerd]
    snapshotter = "overlayfs"
    default_runtime_name = "runc"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/opt/cni/bin"
  conf_dir = "/etc/cni/net.d"

# "Ignoring unknown key in TOML for plugin" error="strict mode: fields in the document are missing in the target struct" key="containerd snapshotter" plugin=io.containerd.cri.v1.runtime
# "Configuration migrated from version 2, use `containerd config migrate` to avoid migration" t="16.408µs"