---
# possibly not required for >=1.30
- name: Copy kernel modules configuration
  ansible.builtin.copy:
    src: modules-load/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    backup: no
    owner: root
    group: root
    mode: "0644"

- name: modprobe overlay
  ansible.builtin.command: modprobe overlay

- name: modprobe br_netfilter
  ansible.builtin.command: modprobe br_netfilter

- name: Copy sysctl configuration
  ansible.builtin.copy:
    src: sysctl/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    backup: no
    owner: root
    group: root
    mode: "0644"

- name: sysctl --system
  ansible.builtin.command: sysctl --system

# deb packages outdated
- name: Download containerd
  get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-{{ containerd_arch }}.tar.gz"
    dest: "/tmp/containerd-{{ containerd_version }}.tar.gz"
    checksum: "{{ containerd_checksum }}"
    mode: "0644"

- name: Create containerd directory
  file:
    path: /etc/containerd/
    state: directory
    mode: "0755"

- name: Extract containerd
  unarchive:
    src: "/tmp/containerd-{{ containerd_version }}.tar.gz"
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/bin/containerd
