- name: Update apt packages
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install common packages
  apt:
    name:
      - git
      - htop
      - tree
      - vim
    state: present
# - name: Ensure SSH is installed
#   apt:
#     name: openssh-server
#     state: present

# - name: Start and enable SSH service
#   service:
#     name: ssh
#     state: started
#     enabled: yes

# - name: Copy custom configuration files
#   template:
#     src: my_config.j2
#     dest: /etc/my_config.conf
#   notify: Restart my_service

# - name: Ensure my_service is running
#   service:
#     name: my_service
#     state: started
#     enabled: yes

# handlers:
#   - name: Restart my_service
#     service:
#       name: my_service
#       state: restarted
