---
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

applicationSet:
  replicaCount: 1
configs:
  params:
    server.insecure: true
controller:
  replicas: 1
  metrics:
    enabled: true
redis:
  exporter:
    enabled: true
  metrics:
    enabled: true
repoServer:
  replicas: 1
server:
  replicas: 1
  metrics:
    enabled: true
