---
- name: Include group variables for Raspberry Pis
  include_vars:
    dir: "{{ playbook_dir }}/group_vars"

- name: Install storage package
  apt:
    name:
      - open-iscsi
      - cryptsetup
      - dmsetup
    state: present

- name: Enable and start iscsid service
  systemd:
    name: iscsid
    enabled: yes
    state: started

- name: Load iscsi_tcp kernel module
  modprobe:
    name: iscsi_tcp
    state: present

- name: Add iscsi_tcp to /etc/modules to load on boot
  lineinfile:
    path: /etc/modules
    line: iscsi_tcp
    state: present

- name: Check if iscsi_tcp module is loaded
  shell: lsmod | grep iscsi_tcp
  register: iscsi_tcp_loaded
  changed_when: false
  failed_when: false

- name: Add dm_crypt to /etc/modules to load on boot
  lineinfile:
    path: /etc/modules
    line: dm_crypt
    state: present

- name: Check if dm_crypt module is loaded
  shell: lsmod | grep dm_crypt
  register: dm_crypt_loaded
  changed_when: false
  failed_when: false
