---
#
# networking and kernel modules
#
- name: Copy kernel modules configuration
  copy:
    src: modules-load/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    backup: no
    owner: root
    group: root
    mode: "0644"

- name: modprobe overlay
  command: modprobe overlay

- name: modprobe br_netfilter
  command: modprobe br_netfilter

- name: Copy sysctl configuration
  copy:
    src: sysctl/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    backup: no
    owner: root
    group: root
    mode: "0644"

- name: sysctl --system
  command: sysctl --system
