---
#
# networking and kernel modules
#
- name: Copy kernel modules configuration
  copy:
    src: modules-load/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    backup: no
    owner: root
    group: root
    mode: "0644"

- name: Ensure overlay kernel module is loaded
  community.general.modprobe:
    name: overlay

- name: Ensure br_netfilter kernel module is loaded
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Copy sysctl configuration
  copy:
    src: sysctl/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    backup: no
    owner: root
    group: root
    mode: "0644"
  notify: reload sysctl
