---
- name: Enable cgroup in /boot/firmware/cmdline.txt
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: "^console=serial0,115200 console=tty1 root=PARTUUID=([a-f0-9\\-]+)-02 rootfstype=ext4 fsck.repair=yes rootwait cfg80211.ieee80211_regdom=AU"
    line: '\g<0> cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
