---
- import_tasks: update_system.yml
  tags: update-only
- import_tasks: disable_swap.yml
- import_tasks: configure_kernel.yml
  tags: update-only
- import_tasks: configure_networking.yml
- import_tasks: configure_cgroups.yml
- import_tasks: configure_storage.yml
  tags: update-only
- import_tasks: install_container_runtime.yml
- import_tasks: unhold_kube_packages.yml
  tags: unhold-kube
  when: "'unhold-kube' in ansible_run_tags"
- import_tasks: install_kube_packages.yml
- import_tasks: display_dependencies.yml
  tags: update-only
