---
- name: Copy kubeadm configuration
  copy:
    src: kubeadm-config.yaml
    dest: "/home/{{ ssh_username }}/kubeadm-config.yaml"
    backup: no
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"
    mode: "0644"
