---
- name: Download and add Helm signing key
  apt_key:
    url: "https://baltocdn.com/helm/signing.asc"
    keyring: "/usr/share/keyrings/helm.gpg"
    state: present

- name: Add Helm repository to APT sources
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: "helm-stable-debian"

- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install Helm package
  apt:
    name: helm
    state: present
